Новый дизайн главной страницы
Delivery-Manager/knowledgebase pull request #24
Opened 2024-06-13 07:45 UTC by MRCUCUMBER1234

Редизайн главной

2024-06-20 12:32 UTC, vshitov requested changes

2024-06-20 12:32 UTC, vshitov commented on docusaurus.config.js
> +      copyright: `© 2006-${new Date().getFullYear()} АО «Тинькофф Банк»`,
Копирайт не нужно трогать. Мы не Тинькофф Банк :)

2024-06-20 12:32 UTC, vshitov commented on src/theme/Footer/index.js
> +      </div>
Пустые ссылки? Предлагаю закомментировать, может в будущем пригодятся

2024-06-20 12:32 UTC, vshitov commented on docusaurus.config.js
> +              to: "/"
Ссылки в никуда? Кто добавит?

2024-06-20 15:26 UTC, MRCUCUMBER1234 commented on docusaurus.config.js
> +              to: "/"
а есть роут?

2024-06-20 15:32 UTC, MRCUCUMBER1234 commented on docusaurus.config.js
> +              to: "/"
нашла, добавила

2024-06-20 15:32 UTC, MRCUCUMBER1234 commented on src/theme/Footer/index.js
> +      </div>
закоментила

2024-06-20 15:33 UTC, MRCUCUMBER1234 commented on docusaurus.config.js
> +      copyright: `© 2006-${new Date().getFullYear()} АО «Тинькофф Банк»`,
случайно поправила видимо ) 
вернула на место

2024-06-21 06:32 UTC, vshitov approved these changes

2024-06-21 06:34 UTC, merged